# Generated by Django 4.2 on 2023-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_alter_email_eid_alter_email_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to_recipient',
            field=models.CharField(default='', max_length=255),
        ),
    ]
